#!/bin/bash

SHARED="/media/sf_Shared-folder"
SOURCE="bin"
DEST="${SHARED}/build"

if [ ! -d "${SOURCE}" ]; then
  echo "${SOURCE} directory does exist, no file to copy"
  exit 1
fi

rm -Rf ${DEST}
cp -R ${SOURCE} ${DEST}

echo "Copied the build to ${DEST}"
echo
find ${DEST} -type f
